# Generated by Django 3.0.4 on 2020-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_animal', models.CharField(choices=[('CAT', 'Кошка'), ('DOG', 'Собака')], default='CAT', max_length=3)),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=150, verbose_name='Порода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('photo', models.ImageField(blank=True, upload_to='animals_photo/%Y/%m/%d', verbose_name='Фото')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], default='M', max_length=1)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
